### ISSUE TITLE
[BUG] Ice trail particles on puck randomly vanish and reappear in game

### ISSUE THREAD

**Issue by annakdross** [AIESydneyStudents/3SQUARED#60]

**Comment by Athied** [comment]
Changing the sorting fudge in the particle system's renderer seems to have lessened how often the problem occurs, but not fully removed it. It's definitely much rarer now and there seems to be less awkward flickering when it happens.

At first I thought it was the max particle size, but I think the actual problem is that sometimes the ice shader (or something else?) gets rendered on top of the particles because they're all so close together and unity keeps changing its mind about what to show. Lowering sorting fudge is intended to override this and make sure the particles are rendered on top.

Perhaps lowering it further will remove the disappearing completely, I'm not sure. For now I'm closing this 'cause I need to work on the next thing, but I may revisit it if I have time.
